@echo off
REM Generated by CMake
set RUNTIME_BIN_DIR=build\bin\RelWithDebInfo
if exist "%RUNTIME_BIN_DIR%\CosmicCities.exe" (
    "%RUNTIME_BIN_DIR%\CosmicCities.exe"
) else (
    echo CosmicCities executable not found in %RUNTIME_BIN_DIR%
    exit /b 1
)
